import { TradeTicket, BankAccountHealth, FloatPool } from '@/types/desk';

export const INITIAL_TICKETS: TradeTicket[] = [
  {
    id: 'AKS-73912',
    createdAt: '14:38',
    expiresAt: '14:53',
    customerName: 'Bishop Tewogbade',
    whatsappPhone: '+233 24 571 9646',
    direction: 'NGN_TO_GHS',
    amountIn: 1500000,
    amountOut: 14277.56,
    rate: 105.06,
    collectionBank: {
      name: 'GTBank Nigeria',
      accountNumber: '0123984752',
      accountName: 'Aksen Liquidity Services Ltd',
      narration: 'AKS-73912',
    },
    momoRecipient: {
      network: 'MTN MoMo',
      phoneNumber: '0245719646',
      registeredName: 'BISHOP TEWOGBADE',
      resolvedStatus: 'RESOLVED_MATCH',
    },
    status: 'SAFE_TO_DISBURSE',
    receiptImage: '/receipts/gtb-sample-clean.png',
    remitterName: 'Bishop Tewogbade',
    gevSystem1: {
      pixelNoiseVariance: 0.04,
      typographyDeviation: 0.2,
      identityScore: 99.4,
      nibssAuthenticity: 99.8,
      probabilityFraud: 0.008,
      verdict: 'PASS_FAST_PATH',
      flags: ['NIBSS Session 0000139820 matched', 'Subpixel raster baseline authentic', '3-Way KYC Name: 100%'],
    },
    whatsappTranscript: [
      { sender: 'customer', time: '14:35', text: 'Good afternoon chief. How much for ₦1.5M to Ghana MTN MoMo?' },
      { sender: 'bot', time: '14:36', text: 'Welcome! Live rate: 1 GHS = ₦105.06. ₦1,500,000 = GH₵ 14,277.56. Rate is locked for 15 minutes.' },
      { sender: 'customer', time: '14:37', text: 'Okay send account details, let me transfer now.' },
      { sender: 'bot', time: '14:37', text: 'Pay ₦1,500,000 into GTBank | 0123984752 | Aksen Liquidity Services. Required narration: AKS-73912.' },
      { sender: 'customer', time: '14:40', text: '[Uploaded Transfer Receipt]' },
      { sender: 'bot', time: '14:40', text: 'Receipt received! GEV Sentinel verifying transfer...' },
    ],
  },
  {
    id: 'AKS-41098',
    createdAt: '14:15',
    expiresAt: '14:30',
    customerName: 'Trader Kwame (Lagos Deal)',
    whatsappPhone: '+233 50 892 1104',
    direction: 'NGN_TO_GHS',
    amountIn: 2000000,
    amountOut: 19036.74,
    rate: 105.06,
    collectionBank: {
      name: 'Zenith Bank',
      accountNumber: '2081940129',
      accountName: 'Aksen Bureau Operations',
      narration: 'AKS-41098',
    },
    momoRecipient: {
      network: 'MTN MoMo',
      phoneNumber: '0541992011',
      registeredName: 'KOFI MENSAH',
      resolvedStatus: 'NAME_MISMATCH',
    },
    status: 'FLAGGED_RISK',
    receiptImage: '/receipts/opay-altered.png',
    remitterName: 'Chioma Adeleke',
    gevSystem1: {
      pixelNoiseVariance: 0.68,
      typographyDeviation: 3.4,
      identityScore: 18.2,
      nibssAuthenticity: 54.0,
      probabilityFraud: 0.892,
      verdict: 'ANOMALY_ESCALATE',
      flags: [
        'CRITICAL: Remitter (Chioma Adeleke) does not match WhatsApp or MoMo (Kofi Mensah)',
        'Font kerning inconsistency in Amount field (+3.4σ deviation)',
        'Suspected Triangular Fraud or Third-Party Account Hijack',
      ],
    },
    gevSystem2: {
      triggered: true,
      model: 'GEV Reasoner (System 2)',
      synthesis:
        'High-probability triangular fraud scheme detected. Inflow remitted from a Nigerian personal account (Chioma Adeleke) with no commercial connection to WhatsApp contact (+233 50...). Disbursing Cedis to burner MoMo line risks imminent PND account freeze on Zenith Bank.',
      recommendedAction: 'DO NOT DISBURSE. Request video KYC verification or refund remitter directly.',
    },
    whatsappTranscript: [
      { sender: 'customer', time: '14:12', text: 'Boss I want to swap ₦2m Cedis fast. Send Zenith account.' },
      { sender: 'bot', time: '14:13', text: 'Rate locked at 105.06. Pay into Zenith Bank: 2081940129. Ref: AKS-41098.' },
      { sender: 'customer', time: '14:16', text: '[Uploaded OPay Receipt] Paid! Send Cedis to MTN 0541992011 immediately.' },
      { sender: 'bot', time: '14:17', text: 'Receipt under forensic review. A desk operator is inspecting this ticket.' },
    ],
  },
  {
    id: 'AKS-84920',
    createdAt: '14:48',
    expiresAt: '15:03',
    customerName: 'Alhaji Musa (Kano Wholesale)',
    whatsappPhone: '+234 803 119 2831',
    direction: 'NGN_TO_GHS',
    amountIn: 3500000,
    amountOut: 33314.29,
    rate: 105.06,
    collectionBank: {
      name: 'OPay Digital Bank',
      accountNumber: '8031940112',
      accountName: 'Aksen Liquidity Desk',
      narration: 'AKS-84920',
    },
    momoRecipient: {
      network: 'MTN MoMo',
      phoneNumber: '0244192019',
      registeredName: 'MUSA IBRAHIM KANO',
      resolvedStatus: 'RESOLVED_MATCH',
    },
    status: 'AWAITING_PAYMENT',
    gevSystem1: {
      pixelNoiseVariance: 0,
      typographyDeviation: 0,
      identityScore: 95.0,
      nibssAuthenticity: 100,
      probabilityFraud: 0.01,
      verdict: 'PASS_FAST_PATH',
      flags: ['VIP Customer tier (Total Volume: ₦42M)', 'Awaiting bank credit webhook'],
    },
    whatsappTranscript: [
      { sender: 'customer', time: '14:46', text: 'Salam alaikum. I have ₦3.5M for Kumasi fabric order. Give me good rate.' },
      { sender: 'bot', time: '14:47', text: 'Wa alaikum salam Alhaji! Special locked rate: 1 GHS = ₦105.06. Cedis payable: GH₵ 33,314.29.' },
      { sender: 'customer', time: '14:48', text: 'Approved. Send account.' },
      { sender: 'bot', time: '14:48', text: 'Pay ₦3,500,000 to OPay: 8031940112 (Aksen Liquidity Desk). Narration: AKS-84920.' },
    ],
  },
  {
    id: 'AKS-91823',
    createdAt: '12:20',
    expiresAt: '12:35',
    customerName: 'Emeka Nwosu',
    whatsappPhone: '+234 902 441 9902',
    direction: 'NGN_TO_GHS',
    amountIn: 5000000,
    amountOut: 47591.85,
    rate: 105.06,
    collectionBank: {
      name: 'GTBank Nigeria',
      accountNumber: '0123984752',
      accountName: 'Aksen Liquidity Services Ltd',
      narration: 'AKS-91823',
    },
    momoRecipient: {
      network: 'Telecel Cash',
      phoneNumber: '0501928491',
      registeredName: 'EMEKA NWOSU VENTURES',
      resolvedStatus: 'RESOLVED_MATCH',
    },
    status: 'DISBURSED',
    receiptImage: '/receipts/gtb-sample-clean.png',
    remitterName: 'Emeka Nwosu Ventures',
    gevSystem1: {
      pixelNoiseVariance: 0.03,
      typographyDeviation: 0.1,
      identityScore: 99.8,
      nibssAuthenticity: 100,
      probabilityFraud: 0.002,
      verdict: 'PASS_FAST_PATH',
      flags: ['Settled via Telecel Cash API at 12:28', 'NIBSS Session: 0000139102 confirmed'],
    },
    whatsappTranscript: [
      { sender: 'customer', time: '12:18', text: 'Rate for ₦5m to Telecel Cash?' },
      { sender: 'bot', time: '12:19', text: '1 GHS = ₦105.06. Payable: GH₵ 47,591.85. Rate locked 15 mins.' },
      { sender: 'customer', time: '12:24', text: '[Uploaded Receipt]' },
      { sender: 'bot', time: '12:28', text: 'Disbursed! GH₵ 47,591.85 sent to Telecel 0501928491. Ref: TEL-881290.' },
    ],
  },
];

export const INITIAL_BANK_ACCOUNTS: BankAccountHealth[] = [
  {
    id: 'bank-gtb',
    bankName: 'GTBank Nigeria',
    accountNumber: '0123984752',
    accountName: 'Aksen Liquidity Services Ltd',
    dailyLimit: 25000000,
    dailyUsed: 6500000,
    status: 'ACTIVE_ROUTING',
  },
  {
    id: 'bank-opay',
    bankName: 'OPay Digital Bank',
    accountNumber: '8031940112',
    accountName: 'Aksen Liquidity Desk',
    dailyLimit: 15000000,
    dailyUsed: 3500000,
    status: 'ACTIVE_ROUTING',
  },
  {
    id: 'bank-zenith',
    bankName: 'Zenith Bank',
    accountNumber: '2081940129',
    accountName: 'Aksen Bureau Operations',
    dailyLimit: 25000000,
    dailyUsed: 22000000,
    status: 'NEAR_CAP',
  },
  {
    id: 'bank-palmpay',
    bankName: 'PalmPay Business',
    accountNumber: '9920194812',
    accountName: 'Aksen Settlement Services',
    dailyLimit: 10000000,
    dailyUsed: 0,
    status: 'COOLING_DOWN',
  },
];

export const INITIAL_FLOAT_POOLS: { ngn: FloatPool; ghs: FloatPool } = {
  ngn: {
    currency: 'NGN',
    symbol: '₦',
    totalBalance: 24850000,
    availableBalance: 18350000,
    reservedBalance: 6500000,
    depletionAlertThreshold: 5000000,
    topAccounts: ['GTBank (₦12.5M)', 'OPay (₦8.2M)', 'Zenith (₦4.15M)'],
  },
  ghs: {
    currency: 'GHS',
    symbol: 'GH₵',
    totalBalance: 184200,
    availableBalance: 136608,
    reservedBalance: 47592,
    depletionAlertThreshold: 30000,
    topAccounts: ['MTN MoMo Merchant (GH₵ 120.4K)', 'Ecobank GH (GH₵ 63.8K)'],
  },
};
